package com.ss.business.rules1;

import com.ss.business.model.User;
import com.ss.business.model.Result;

rule "Hello1"
    when
        $u : User( name == "abc" )
        $r : Result ()
    then
        $r.setMessage("Hello " + $u.getName());
end

rule "Bye1"
    when
        $u: User( name == "xyz" )
        $r : Result ()
    then
        $r.setMessage("Bye " + $u.getName());
end

rule "unknownUser1"
    when
        User( name != "abc" && name != "xyz" && name !="123" && name !="456")
        $r : Result ()
    then
        $r.setMessage( "Sorry, I dont know you");
end

